== Selección del Diario de John Richardson

No tenía más de trece años cuando murió mi padre, sin embargo,
el Señor estaba obrando en mi corazón por medio de Su luz, gracia y Espíritu Santo.
Yo en ese entonces no conocía lo que inquietaba interiormente mi mente,
cuando algo malo prevalecía sobre el bien en mí,
algo que sucedía a menudo por no prestar atención al Espíritu de Dios
en mi corazón. Yo deseaba tranquilidad y paz de alguna otra manera,
sin tener que tomar la cruz de Cristo contra mi propia voluntad corrupta,
así que por un tiempo me esforzaba (como sin duda hacen muchos)
en regocijarme pisoteando al Testigo justo de Dios en mi corazón,^
footnote:[Ver Apocalipsis 11:10]
hasta que parecía que moría o desaparecía por un tiempo.
Era entonces cuando me daba más libertad,
aunque no en las repugnantes maldades hacia las que muchos corrían,
pues era preservado por una inclinación religiosa.
Yo buscaba a los profesantes del cristianismo y les hacía
preguntas para mi propia información y satisfacción,
tratando de encontrar algo sobre lo cual fuera seguro descansar,
o un consuelo verdadero y sólido para mi pobre alma desconsolada y turbada.
Sin embargo, tenía miedo de ser engañado,
o de tomar un falso descanso en algo que estuviera equivocado o no fuera seguro;
dicho temor era el gran amor y misericordia de Dios hacia mí.

Muchas veces busqué y pregunté entre los que sólo estaban en la letra escrita,
en el patio exterior, donde el velo permanece sobre el entendimiento,
y el ojo de la mente no está verdaderamente abierto para ver las
cosas que están escondidas de todos los hombres de mente carnal.
Por tanto, mi estado y mis aflicciones estaban ocultas para estos,
junto con las diversas obras engañosas de Satanás
y las fuertes tentaciones con las que me topaba.
Estos guías ciegos no podían ver ni sabían cómo dirigirme
hacia el verdadero Pastor de Israel,
al Dador de la ley que sale de Sión,
que aparta la impiedad de Jacob y la transgresión de Israel,
pues tampoco habían experimentado verdaderamente en ellos,
la liberación del estado nublado, confuso y de tentación en el que yo me encontraba.

¡Oh, si las personas vinieran Al que tiene colirio para el ojo,
con el que si el ojo fuera verdaderamente ungido,
vería las cosas tan claramente como son y no oscuramente,
confundiendo árboles con hombres y las cosas terrenales con las celestiales! ¡Ojalá
compraran el oro que es tratado por el fuego de Aquel que es llamado la Piedra Probada,
elegida y preciosa, tendida en Sión como fundamento!
Esta es Cristo, en quien la verdadera iglesia cree y es edificada, y por tanto,
enriquecida con Su amor, poder y virtud, lo cual es mejor que el oro externo.
De hecho, esta es la unción que la verdadera iglesia tiene y recibe de Cristo, el Santo,
y cuando esta se viste de Su justicia, pureza y santidad,
su ropa es mejor que el lino fino externo.
¡Oh, qué todos los habitantes de la tierra sean ungidos,
enriquecidos y verdaderamente vestidos,
de manera que ya no sea encontrada ceguera o pobreza interna en los hijos de los hombres,
ni sea más vista la vergüenza de su desnudez! ¡Reciban y aprendan estas cosas,
los que puedan, de Aquel que es el Testigo fiel y verdadero,
que siempre testifica contra el mal en el hombre,
pero aboga ante el Padre para el bien de los hombres en todo lo que dicen y piensan!
Este es el Espíritu de Aquel que estaba muerto, pero ahora vive,
y que ya no debe ser conocido por los hijos de los
hombres según la carne (como testificó el apóstol),
sino interna y espiritualmente.

Él es el único que abre el ojo ciego,
destapa el oído sordo y penetra en el alma que ha estado nublada y cautiva,
encarcelada y equivocada, es decir, en un estado estéril,
sin ver una manera de liberación,
al igual que Israel en la tierra de Egipto cuando el Señor Jehová envió a Moisés,
un tipo vivo de Cristo,
y lo usó en esa gran obra de súplica y plagas contra el Faraón y los egipcios.
Por un tiempo las cargas de Israel fueron aumentadas y sus pruebas más amargas,
hasta que su liberación fue cumplida en buena medida,
cuando el primogénito del hombre y de la bestia fueron
asesinados a lo largo y ancho de la tierra de Egipto.
La clara revelación que tuve en la luz de lo que se debe entender y recoger de esto es:
No la muerte del hombre exterior, no, sino la necesidad de ser despojados,
o de que el cuerpo de pecado de la carne muera,
crucificando o matando al viejo hombre con sus obras.
Y en cuanto a la bestia, que toda la crueldad, lujuria y empuje,
así como su inclinación a desgarrar,
devorar y salvajismo deben ser asesinados o eliminados.
La corrupta o fuerte voluntad del hombre, junto con todo lo que es brutal,
deben ser asesinados antes de que el hombre pueda
salir de debajo del poder del que es llamado,
"`príncipe de la potestad del aire,
el espíritu que ahora opera en los corazones de los hijos de desobediencia.`"
Estas cosas deben ser experimentadas antes de que los hijos de los hombres
puedan salir correctamente calificados para glorificar a Dios,
y para seguir a Su amado Hijo,
a quien Él ha designado como líder y comandante de Su pueblo.
Este es Aquel, como declaró Moisés, que debe ser escuchado en todas las cosas,
so pena de ser cortados del pueblo,
de que sus nombres sean borrados del libro de la vida,
o de ser privados del consuelo de la santa presencia del Señor. ¡Lean esto,
los que han oído y entendido lo que el Espíritu les dice a las iglesias!
Estas cosas las vi después de que el Testigo verdadero reviviera y se levantara en mí,
y brillara la luz que por un tiempo había estado desaparecida o había sido nublada.

Después de mucho buscar afuera,
entre los que me habían probado ser médicos nulos y miserables consejeros,
me entregué a una vida solitaria y retirada,
respirando tras el Señor y buscándolo en campos y parajes apartados,
suplicándole que me llevara al conocimiento salvador de Su verdad.
¡Bendito sea el nombre del Señor ahora y para siempre,
porque no lo había buscado por mucho tiempo con todo mi corazón,
antes de encontrarme con Su aparición interior en mí,
en y por medio de Su Santo Espíritu, luz y gracia!
Pero cuando la verdadera luz empezó a brillar más claramente,
y el Testigo vivo se levantó en mi hombre interior, ¡oh,
entonces empezó a aparecer mi condición perdida, confundida y miserable,
y mis conflictos y angustias fueron grandes e indescriptibles!
Yo pensaba que ningún hombre sobre la faz de la tierra estaba en
una condición como la mía. Yo creía que no estaba listo para morir,
pero tampoco sabía cómo vivir.
En la noche pensaba: "`¡Ojalá fuera de mañana!,`" y en la mañana:
"`¡Ojalá fuera de noche!`"
Salía a caminar solo por los campos y otros lugares,
en los que con fervientes súplicas derramaba mis quejas y clamores delante del Señor,
pidiéndole que mirara mi aflicción y las fuertes tentaciones bajo las que estaba,
y que reprendiera al adversario de mi alma y la librara.
Yo creía que mi alma estaba en las fauces del león devorador,
entre los espíritus ardientes y bajo el peso de las montañas.
¡Lean y entiendan las aflicciones de su hermano,
ustedes que han llegado a través de grandes tribulaciones,
y han lavado y emblanquecido sus vestidos en la sangre del Cordero!
Este es el principio de ese bautismo que salva,
y del lavamiento de la regeneración y de la renovación del Espíritu
Santo que el Señor derrama en abundancia sobre los creyentes.
Esta es la sangre que rociada en el corazón lo limpia de una mala consciencia,
para que los hijos de los hombres, así cambiados, sirvan al Dios vivo y verdadero.
Esta es la vida que convierte al mundo, es decir, a los que son convertidos.
Esta es la virtud, la vida y la sangre que limpia los vestidos de los santos,
y que internamente lava de toda inmundicia, tanto de carne como de espíritu.
Descubrí que este era y es Aquel de quien es dicho:
'`Todas las cosas por Él fueron hechas, y Él es el Señor de todo.`' Ciertamente,
el hombre debe ser siervo de Él,
y todas las cosas en el hombre deben estar subordinadas a Él,
quien gobierna y comprende todas las cosas,
y en quien todos los tipos y sombras terminan y están cumplidos.
¡Lee esto, hija virgen, o iglesia limpia de Cristo, la Roca de tu fortaleza,
cuyo Nombre es para ti como precioso ungüento derramado,
pues debido al sabor de Sus ungüentos las vírgenes Lo aman,
y están bajo la gran obligación de obedecer y seguir al Cordero de Dios,
dondequiera que las guíe!

Aunque yo había visto muchas cosas y tenido varias revelaciones,
mis pruebas seguían siendo grandes,
y las tentaciones en las que me encontraba en aquellos días eran muchas.
Yo vivía lejos de Amigos y reuniones, lo que hacía mis ejercicios más difíciles,
como aparecerá más plenamente después. De hecho,
algunas de las pruebas que me encontré en el transcurso de mis
viajes y peregrinaje en este valle de lágrimas y problemas,
no eran comunes, pero el Señor me ayudó a través de todas ellas.
¡Bendito sea Su nombre para siempre!

Como resultado de eso, llegué a experimentar el cumplimiento de esa Escritura que dice:
"`Cuando hay juicios del Señor en la tierra,`" o
en los corazones terrenales de los hombres,
"`los habitantes aprenden justicia.`"
Había una aversión en mi naturaleza indómita hacia
el pueblo que en desprecio era llamado cuáqueros,
y hacia el nombre mismo también. Y sin embargo,
cuando la mano de aflicción del Señor estaba sobre mí por mi desobediencia,
y cuando (como Efraín y Judá) veía mi daño y mi herida en la luz,
me lamentaba y lloraba por esa Semilla justa de luz y gracia en mí,
que yo había traspasado con mis pecados y desobediencia.
Aunque ese ministerio de condenación trabajaba adentro y era glorioso en ese momento,^
footnote:[En 2 Corintios 3 Pablo describe el antiguo pacto como "`el ministerio
de condenación,`" y el nuevo pacto como "`el ministerio del Espíritu.`"
Los primeros Amigos creían,
que así como un ministerio le dio paso al otro con
la venida de Cristo en el cumplimiento del tiempo,
este mismo proceso o cambio ocurre en el corazón del creyente.
En primer lugar,
la justa ley de Dios brilla como una luz sobre la
naturaleza transgresora en el hombre y sus frutos.
Luego, conforme la raíz,
las ramas y los frutos del hombre carnal son entregados a la muerte en la cruz,
el ministerio del Espíritu viene a ser progresivamente experimentado,
en donde el Señor reina en creciente libertad en y sobre el corazón circuncidado.]
mis problemas eran grandes,
lo cual humillaba mi mente y me inclinaba a estar dispuesto a negarme
todo aquello que la luz me daba a conocer que era malo.

Yo estaba en gran angustia, y carecía de paz y seguridad del amor de Dios hacia mi alma.
El peso de esto humillaba grandemente mi mente, y no sabía de ningún llamamiento, pueblo,
práctica o principio que fuera lícito y correcto,
que yo pudiera abrazar o al cual acogerme.
Esto era seguramente, como el día de las angustias de Jacob y los temores de David,
y vi que '`las inmundicias de Sión tenían que ser limpiadas por el Espíritu
de juicio y Espíritu de devastación.`' (Isaías 4:4) Este es el camino
que libera y recupera a los pobres hombres de la caída,
y el camino por el que Dios restaura el reino de Su verdadero Israel.
¡Lean y entiendan los que puedan!
Este fue el día de mi bautismo en el amor de Dios y en la verdadera fe en Su amado Hijo,
así como también, en la experiencia o participación con Él en Sus sufrimientos,
los cuales son inexpresables.
Luego encontré que el ministerio había cambiado,
porque lo que había sido para muerte ahora era para vida.
Sí, el ministerio de condenación era para el primer nacimiento,
pero cuando este había sido asesinado,
y en gran medida clavado o sujetado a la cruz de Cristo (que es poder de Dios),
entonces lo bueno prevalecía sobre lo malo,
y eliminaba el mal en la mente y en los miembros, haciéndolo todo bueno y santo.
En realidad, cuando el poder vivo del Señor y la Palabra consumidora obran y prevalecen,
traen todo a sujeción y hacen santo el corazón mismo o terreno en los hombres.

Como había una aversión en mí hacia el pueblo llamado en menosprecio, cuáqueros,
y también hacia sus estrictos hábitos de vida, conducta y sencillez de lenguaje,
no aprendí de ellos ninguna de esas cosas.
Sino que cuando el Señor cambió mi corazón, también cambió mis pensamientos,
palabras y maneras, de modo que encontraba una aversión hacia el vicio,
el pecado y la vanidad en mí,
como la aversión que había tenido antes hacia los caminos de la virtud.
Habiendo gustado los terrores y juicios de Dios debido al pecado,
fui advertido a huir de las cosas que hacen que Cristo
venga "`no para traer paz sobre la tierra,
sino espada.`"
¡Una espada en definitiva.
Sí, Su Palabra que penetra y escruta en el corazón,
y que es más cortante que cualquier espada de dos filos,
que penetra hasta partir la carne y el espíritu, las coyunturas y los tuétanos!

Así llegué a ver y aborrecer el mal en mí,
y cuando aquellos que habían sido mis compañeros en la vanidad ahora me injuriaban,
o se metían en mi camino, yo a menudo era movido a advertirles y a reprenderlos.
Habiendo gustado de los terrores del Señor por el pecado,
no podía abstenerme de advertir a otros que huyeran
de las cosas por las que yo había sido juzgado.
Entonces quedé claramente disuadido del hábito de dar honor por medio del sombrero,
o doblando la rodilla, del lenguaje corrupto, así como también de las galas en la ropa,^
footnote:[Ver la Introducción, página 4.]
todo lo cual, para bien de mi consciencia y la paz de la misma, llegué a negar,
a tomar la cruz y a experimentar una gran paz al hacerlo.

Aunque la bendita verdad prevalecía así en mí,
yo todavía no estaba exento de grandes conflictos de espíritu,
tentaciones y pruebas de diversa índole.
Sin embargo, mi mente estaba rendida al Señor y mis oraciones a Él eran fervientes.
Ciertamente, Él me guardó y abrió mi entendimiento,
pues yo tenía miedo de ser engañado en algo,
especialmente en las cosas relacionadas con mi salvación.
Llegué a ser destetado de todos mis compañeros y amados,
con quienes me había deleitado.
Todas las cosas en este mundo eran poco para mí,
pues mi mente había sido redimida del mundo,
no sólo de la parte corrupta y maligna de este, sino incluso de la parte lícita.
Por tanto, me dediqué a buscar al Señor más,
a esperar en Él hasta sentir Su presencia y paz,
a conocer Su voluntad y recibir poder para hacerla.

Cuando mi mente fue llevada a un estado de dependencia y de espera en el Señor,
a permanecer en la luz,
y participar por experiencia y de manera discernible de
Su amor y gracia (lo que me ayudó contra mis debilidades),
encontré que era suficiente para mí,
en la medida que me mantuviera vuelto hacia esto en todas mis pruebas y tentaciones.
¡Bendito sea Su nombre!
Luego vi que todas las actuaciones externas en materia de religión, no valen,
ni hacen que el hombre sea aceptable para Dios,
sino únicamente cuando el corazón se rinde verdaderamente a Él,
para que Él no sólo lo purgue de la contaminación,
sino también lo mantenga limpio a través de la morada
de Su Santo Espíritu en él. Hasta donde recuerdo,
vi claramente estas cosas antes de mi décimo sexto año de vida.

Entre la muerte de mi padre y ese tiempo, fui libre de ir a cualquier grupo que quisiera.
Como mi madre nos daba gran libertad,
comencé a asistir a las reuniones del pueblo del Señor llamado cuáqueros,
tan diligentemente como mis circunstancias me lo permitían. Mi
madre era una mujer que gozaba de respeto entre los que la conocían,
porque era hacendosa y justa en los tratos concernientes a las cosas de este mundo.
Cuando mi padre murió ella quedó con cinco niños,
siendo el más pequeño de unos tres años. Mi padre
dejó muy poco de los bienes de este mundo para criarnos,
aunque mis padres siempre tuvieron lo suficiente
como para mantenerse por encima del desprecio,
y que nadie perdiera nada por causa de ellos.
Fue así como me encontré bajo la necesidad de trabajar duro para mi propio sostén,
para la ayuda de mi madre y para la educación de mis hermanos,
especialmente desde que mi única hermana muriera poco después. Sin embargo,
al ser dejados en una granja de pastoreo, parte de la cual estaba cultivada,
nos fue bien en cuanto a las cosas de este mundo.

No puedo dejar de mencionar algo que vino a ser una gran prueba para mí:
Mi madre se casó con un hombre celoso por el Presbiterio.
Yo estaba muy en contra del matrimonio,
y le dije a mi madre que yo temía que ella tuviera
demasiado puestos los ojos en lo que él tenía,
pues desde el punto de vista de este mundo, él era considerado rico.
Y que si ella pensaba en aumentar nuestra herencia al casarse así,
la mano del Señor estaría contra ella,
y una calamidad o plaga vendría incluso sobre lo que habíamos
conseguido a través de esfuerzo y trabajo duro.
Pero que si nos manteníamos fieles a la verdad y
nos contentábamos con la condición del momento,
el Señor nos bendeciría. Mi madre confesó, que en cuanto a las comodidades mundanas,
ella nunca había estado en mejores condiciones que en ese momento.
Debo escribir con gran cautela; ella era mi madre y una tierna madre conmigo,
en ninguna forma dispuesta a ofenderme.
Ella prometió hasta donde se atrevió,
a no casarse con alguien con quien yo no estuviera satisfecho.
Sin embargo, del proceder de ellos a partir de ese momento,
en cuanto al cortejo y matrimonio, fui completamente ignorante hasta que fue consumado.
Y luego, cuando mi pobre madre ya estaba casada, su clamor era: "`Mi hijo,
¿cómo podré mirarlo a la cara otra vez?
Esto será una aflicción para él. Él nunca me ha desobedecido,
porque si yo lo mandaba a ir, él corría, y si lo mandaba a hacer algo,
lo hacía con toda su fuerza;`" más o menos en este sentido,
como varios me contaron que la oyeron decir.
Tras el matrimonio, lo que teníamos fue mezclado con los bienes de mi padrastro.
Con el tiempo, mi madre murió, mi padrastro se volvió a casar,
hizo su testamento y cuando murió, me dejo cinco chelines como mi parte.
Por lo que puedo recordar, este matrimonio ocurrió en mi décimo octavo año de vida,
y lo que yo había previsto acerca de la calamidad y la plaga, sucedió.

Regreso a mi relato con respecto a los problemas que me acompañaron
mientras viví en la casa de mi padrastro y mi madre.
Después del matrimonio de ellos,
nosotros y lo que teníamos fuimos llevados a la casa de él,
excepto parte del ganado que fue dejado en el campo.
Tuve el presentimiento de que pasaría por una gran prueba,
y me sentí muy abatido con respecto al matrimonio y con
luchas en mi mente con respecto a mi propia condición;
tenía tantos conflictos de espíritu que estaba a punto de la desesperación. Si el Señor,
en quien creía,
no se hubiera levantado en Su poder para reprender al adversario de mi alma,
yo habría sido vencido y tragado en el día de dificultad y gran dolor,
por las tentaciones que eran arrojadas de la boca del dragón. Pero en un tiempo aceptable,
el Dios de amor y piedad me vio y me ayudó en mi angustia.
Él, que oyó al pobre Ismael cuando clamaba debajo del arbusto,
dándole alivio a él y a su madre cuando habían sido sacados de la casa de Abraham,
me vio en esta gran estrechez.

Cuando llegué a la casa de mi padrastro,
encontré que él era un hombre muy dedicado a los deberes religiosos,
tales como dar gracias antes y después de las comidas.
Pero yo no podía cumplir con ninguna de esas cosas,
a menos que evidentemente sintiera que el Espíritu de la Verdad estaba
presente y abriendo la boca y el corazón para poder hacer tales cosas.
Porque yo había llegado a ver claramente que no se podía
realizar adoración verdadera y aceptable a Dios,
a menos que fuera en Espíritu y en Verdad; que nadie podía orar correctamente,
a menos que el Espíritu le ayudara y enseñara cómo orar y qué orar,
y preparara correctamente la mente y la guiara en la realización
de cada servicio que el Señor les pide a Sus hijos.
El primer día que llegué a la casa, al ser llamado a la mesa con todos,
o con la mayoría de la familia, pensé: "`¿Con que a esto hemos llegado?`"
¡Debo desagradar a mi padre celestial o a mi padre terrenal!`"^
footnote:[John Richardson se sintió obligado a mantener su sombrero puesto,
para demostrarle a su padrastro que no podía unirse a él en su oración formal y muerta.]
¡Oh, la espantosa y profunda prueba que estaba sobre mi espíritu!
Porque los clamores que ascendían al Señor en busca
de ayuda y preservación para no ofenderlo a Él,
eran fuertes.
Mi padrastro estaba sentado con su sombrero parcialmente quitado y sus ojos fijos en mí,
como los míos estaban fijos en él con mucho temor.
Continuó dando gracias (como ellos lo llamaban) tanto o más tiempo que el que acostumbraba,
pero no dijo nada que oyéramos.
Finalmente se puso de nuevo su sombrero para sorpresa de la familia,
y no me preguntó ni en ese momento, ni después,
el porqué no me había quitado mi sombrero.
Ni en todo el tiempo que estuve con él (un poco más de un año),
volvió a realizar esa ceremonia;
así me ayudó el Señor. ¡Qué Su nombre sea celebrado ahora y para siempre!

Mi padrastro parecía ser por edad, espíritu y entendimiento,
más que un rival para mí (un pobre infeliz), pero creo que el Señor,
que hizo que una columna de nube le diera luz a Israel,
llevara tinieblas sobre los egipcios, y peleara contra ellos a favor de Israel,
golpeó a mi pobre padrastro para que él no pudiera
levantarse contra el poder con el que Él me ayudaba.
En verdad, no era mi obra, sino del Señor. ¡A Él sean dados los atributos de alabanza,
salvación y fuerza, ahora y para siempre!

Descubrí que mi padrastro estaba muy disgustado por mi asistencia a las reuniones,
y yo no podía encontrar una forma de apaciguar su disgusto, excepto quizás,
siendo muy diligente en su negocio, para el que yo trabajaba muy duro,
incluso más allá de mis habilidades.
Es casi increíble lo que mi pobre, pequeño y débil cuerpo atravesó en aquellos días,
pero nada ganó su amor.
De hecho, cuanto más tiempo estaba con él, más declinaba su amor hacia mí,
aunque yo le decía que no se preocupara por mi salario porque lo
dejaría a su discreción. Yo no podía ver qué tenía contra mí,
excepto mi asistencia a las reuniones; y eso era todo lo que él alegaba.

Cuando otras estrategias fallaron,
él me ofreció un caballo con la condición de que
fuera con él a su lugar de adoración. Yo lo rechacé,
por lo que me encontré con muchos semblantes desagradables y amargos
a mi regreso a pie de las reuniones (aunque yo siempre regresaba
tan puntualmente como mi cuerpo era capaz de hacerlo).
En las mañanas del primer día mi padrastro solía enviarme a los campos,
a una o dos millas a pie, para que observara el ganado, los caballos y las ovejas,
supongo que con la intención de que me cansara y fuera incapaz de ir a las reuniones.
Todo esto lo sobrellevé pacientemente, y que yo recuerde,
nunca me quejé de que fuera un maltrato.
Entonces, después de sus encargos y para gran dolor de mi pobre madre,
yo tenía que caminar dos, tres, cuatro, cinco y a veces seis millas,
para llegar a las reuniones de los Amigos.
Después de caminar rápido,
o correr con mis zapatos debajo de mis brazos por falta de tiempo,
vi a muchos Amigos llorar cuando me veían entrar
a la reunión con mucho calor y muy sudado.
No podían contener las lágrimas,
siendo en parte sensibles de la difícil tarea que yo tenía que soportar.
Pero el gran poder del Señor me sostenía, y Él me daba (por decirlo así) pies de ciervo,
y me daba capacidad para pasar por estos ejercicios
y soportar la carga en el calor del día de las pruebas,
tanto interna como externamente, las cuales eran muchas y variadas.

La última estrategia que mi padrastro usó para impedir
que yo fuera a las reuniones fue la siguiente:
Me tomó en sus brazos con una gran muestra de amabilidad,
y dijo que si yo era como un hijo para él, él sería como un padre para mí,
expresando también algo acerca de su falta de parientes cerca.
Dijo algo en el mismo sentido hacia mi hermano Daniel, quien era un jovencito inocente,
sabio y limpio de espíritu.
Yo le respondí: "`Si al hacer de mí tu hijo,
tienes la intención de impedir que yo vaya a las reuniones,
u obligarme a ir contigo a las reuniones presbiterianas,
o que yo haga algo que esté en contra de mi consciencia,
sobre ese fundamento no puedo ser tu hijo.`"
Y por las mismas razones también me negué a ser su empleado,
aunque ofreció contratarme y darme un salario si yo dejaba de ir a las reuniones.
Así que cuando él vio que ni los ceños fruncidos, ni las amenazas, ni las dificultades,
ni las grandes promesas de amabilidad pudieron prevalecer contra mí,
me dijo franca y ásperamente que no podía permanecer más tiempo en su casa.
Inocentemente le respondí que si debía ser así, yo no podría evitarlo,
pues nada de lo que yo hiciera le daría a él contentamiento
sin herir mi consciencia o la paz de mi mente,
lo cual yo valoraba por encima de todas las cosas mutables de este mundo.
Mi pobre madre oyó mis súplicas y cómo le ofrecí
hacer lo máximo posible para él de noche o de día,
como siempre lo había hecho,
si él estaba tranquilo y me daba su aprobación. Pero
su respuesta fue que no debía quedarme en su casa.

Esto afligió tanto a mi madre que me vi forzado a dejar a mi padrastro,
ir adonde ella estaba y esforzarme por aliviar su gran tristeza diciéndole,
que yo creía que si era fiel, el Señor me cuidaría para que no me hiciera falta nada.
Y para desahogarme completamente,
le recordé que ella había entrado en un pacto de matrimonio con su esposo,
por lo que ella debía esforzarse en cumplirlo y entregarse
fielmente en todo como una esposa debe hacerlo con su esposo,
dejarme, dejar todo lo demás,
unirse a él y hacer su propia vida tan tranquila como pudiera.
También le dije que nunca me mandara nada de lo que mi padrastro no estuviera enterado,
porque no sería libre de recibirlo.

Escribo esto en parte,
para que todo el que se case tenga especial cuidado de hacerlo con gran cautela,
bajo la debida consideración, y tras haber buscado diligentemente al Señor en esto.
Todo debe ser hecho en Su consejo, no sólo de nombre, sino en Su temor, verdaderamente,
y entonces y sin ninguna duda será para bien de ambos cónyuges.
Porque estos, al estar unidos en yugo igual,
no sólo serán verdaderos colaboradores en todas las cosas que pertenecen a esta vida,
sino especialmente,
en las cosas que pertenecen al mundo por venir y para el bien del alma inmortal.
¡Oh, cuán feliz y pacíficamente vivirán juntos en el Señor,
mientras se mantengan en lo que los unió!

Viene a mi mente un suceso notable que ocurrió de la siguiente manera: Mi padrastro,
después de regresar a casa de la reunión presbiteriana y como era su costumbre,
puso a mi hermano a leer en voz alta el texto de los sacerdotes.
Ese día había sido de Daniel,
cuando fue arrojado al foso de los leones por no atender el decreto del rey.
Contrario al mandato del rey,
Daniel oró al Dios del cielo con sus ventanas abiertas hacia Jerusalén,
como solía hacerlo.
Mientras mi hermano leía, mi padrastro hacía sus observaciones y engrandecía a Daniel.
Decía que el Espíritu de Dios estaba en él,
pero que no había nadie como él en nuestros días. Yo admití
que Daniel había sido un hombre verdaderamente extraordinario,
pero que no estaba de acuerdo con él cuando afirmaba,
que no había nadie dotado con una medida del mismo Espíritu en nuestro día. Entonces
le conté brevemente a mi padrastro de los muchos sufrimientos de nuestros Amigos
por causa de la palabra de Dios y el testimonio de Jesús,
algunos de los cuales eran pasados y otros presentes.
Especialmente mencioné los grandes sufrimientos de
nuestros queridos Amigos en Nueva Inglaterra,
donde se encontraron con duros encarcelamientos, crueles azotes,
corte de orejas y destierros si volvían a Nueva Inglaterra.
También le mostré cómo habían matado a Marmaduke Stevenson, William Robinson,
William Leddra y a Mary Dyer,
por ninguna otra causa que trabajar para volver a las personas de las tinieblas a la luz,
y del poder de Satanás al poder vivo de Dios; es decir, a Su luz,
gracia y Santo Espíritu en sus corazones.
Y por trabajar para sacar a las personas de la persecución,
orgullo y toda obra y camino del mal, a vivir una vida de negación y humildad,
en concordancia con el cristianismo que profesaban.^
footnote:[Estos cuatro cuáqueros fueron llevados a la muerte en Boston en 1659,
1660 y 1661 por un gobierno puritano, que había determinado que simplemente _ser_ cuáquero,
era una ofensa digna de destierro.
En ese tiempo los Amigos sufrieron grandemente bajo la persecución
de los sacerdotes y magistrados de Nueva Inglaterra,
pero más especialmente, a manos del gobernador de Boston, el infame John Endecott.
A muchos los encarcelaron, los pusieron en cepos, les cortaron las orejas,
los desnudaron hasta la cintura,
los ataron a carretas y los azotaron de pueblo en pueblo antes de ser desterrados.
Regresar a Massachusetts Bay Colony (Colonia de la Bahía de Massachusetts)
después de ser desterrados era una ofensa capital.
Para un relato más completo de estos sucesos ver, "`The History of the Rise, Increase,
and Progress of that Christian People Called Quakers,`" por William Sewel.
(Historia del Levantamiento,
Crecimiento y Progreso del Pueblo Cristiano Llamado Cuáqueros).]
Que para este servicio habían sido llamados y por él habían sufrido profundamente.
Por tal razón yo deducía que algo del Espíritu de Dios había en el hombre de estos días,
como lo había habido en Daniel y en muchos otros antes,
que los ayudó y sostuvo en sus grandes sufrimientos.
Mi padrastro confesó que era cierto que algunos sufrían por el bien y otros por el mal.
Entonces dijo que él había vivido casi sesenta y cinco años,
y aunque nos había oído hablar de la Semilla o luz interior, no sabía qué era.
Yo le respondí muy mansamente: "`Si me escuchas,
te diré lo que es,`" y lo hice con las siguientes palabras.
"`Cuando en algún momento has tenido la tentación de extender tu mano para robar,
o mentir para obtener ventaja, o jurar por alguna provocación,
o permitir cualquier obra o palabra mala,
¿acaso no has hallado algo en ti que te ha mostrado que no debes decirlo o hacerlo?
Y cuando le has prestado atención a eso y no has dicho ni hecho mal,
¿acaso no has hallado gran paz y consuelo interior en tu mente?
Pero si por el contrario, has dicho o hecho mal,
¿acaso no has hallado gran intranquilidad y angustia de mente?
Esta es la Semilla interior,
luz o gracia que Dios ha puesto en el hombre para ayudarlo y dirigirlo, lo que nosotros,
el pueblo de Dios llamado cuáqueros,
sostenemos que está de acuerdo con las Santas Escrituras.`"
Entonces mi padrastro dio una palmada con sus manos y confesó que eso era cierto.

Poco tiempo antes del matrimonio de mi madre,
fui llevado a la obra pública del ministerio.
Yo tenía muchos argumentos con respecto a esto,
pues era un joven de apenas dieciocho años y naturalmente tartamudo,
algo que no había podido superar aunque me había esforzado
con todo lo que estaba en mi poder como hombre;
nada funcionó hasta que la Verdad me ayudó. Pero tras mis muchos conflictos,
dificultades y tentaciones,
me encontré con la peor prueba que alguna vez haya enfrentado,
y con el dolor más penetrante en el que haya estado
desde que llegué al conocimiento de la bendita Verdad,
cuando por argumentos,
desobediencia e indisposición a cumplir con las demandas del Señor,
Él en desagrado quitó de mí el consuelo de Su santa presencia por varios meses seguidos.
¡Oh, las tribulaciones que encontré en esa condición! No hay lengua capaz de expresar,
ni criatura capaz de concebir la profundidad de la punzante tristeza en la que yo estaba.
Yo pensaba que mi estado era tan malo como el de Jonás,
porque si en verdad hay un infierno sobre la tierra,
yo estaba en él. ¿Qué mayor infierno puede haber
para un alma vivificada y un entendimiento iluminado,
que han gustado la bondad de Dios y en alguna medida los poderes del mundo venidero,
que ser privados de todo eso y creer que han caído de ese estado?
Yo escasamente podía creer que alguna vez se me concedería arrepentimiento,
o sería restaurado al amor y favor de Dios,
pues encontré seco el río de vida que me había alegrado verdaderamente,
tanto a mí como a la ciudad de Dios.

Estando bajo la desazón del disgusto del Señor y
participando en parte de los terrores de Su ira,
pensaba: "`¡Oh,
estoy seguro de que si las montañas y las colinas fueran pesadas en una balanza,
no serían suficientes contra el peso de mis dificultades y aflicciones!`"
Pero así como el Señor, mediante Sus juicios,
me había sacado en buen grado del vicio y de la vanidad de este mundo,
en ese momento y por medio de Sus juicios, me dio el querer rendirme a Sus demandas.
En mi obediencia a él,
empecé a sentir de nuevo un poco del consuelo del amor y
de la comunión del Espíritu del Señor en mí y en Su pueblo,
quienes eran partícipes de la misma comunión.

Volviendo al asunto de mi expulsión de la casa de mi padrastro, cuando vi que debía irme,
pensé que era conveniente poner al tanto de esto a algunos muy dignos Amigos,
para que no se hicieran especulaciones indebidas sobre la Verdad, los Amigos o yo mismo,
porque de ser así, ellos podrían contradecirlas.
Por tanto, se lo di a conocer a Sebastian Euethorp y al estimable ministro del evangelio,
Benjamín Padley, dos de los principales Amigos en la Reunión Mensual en Ellington.
Estos hombres vinieron a la casa de mi padrastro
y le preguntaron la razón por la que yo debía irme,
si él tenía algo contra mí en relación al negocio para el que me había contratado,
o si yo no era fiel y diligente en los asuntos a los que él me enviaba.
Él no sólo confesó que yo era fiel y diligente,
sino que pensaba que nadie podría superarme.
Ellos dijeron: "`Bien, entonces, ¿cuál es la razón del conflicto entre tú y tu hijastro?
¿Es acerca de su asistencia a las reuniones?`"
Cuando ellos entendieron las razones de mi padrastro (lo que no era difícil),
le expresaron su compasión hacia mí por no tener más libertad.
Y le sugirieron, que como yo era muy diligente en su negocio,
que tal vez si él me daba un poco más de libertad para ir a las reuniones,
eso sería un estímulo para mí. Antes esto,
mi padrastro se ofendió y trató a estos buenos hombres con un lenguaje rudo,
y les preguntó qué tenían que ver ellos con él y conmigo.
Entonces les ordenó salir de su casa y ocuparse de sus propios asuntos y dijo,
en resumen, que ahí ya no había lugar para mí. Los Amigos se turbaron ante esto,
especialmente por mi bien,
y luego se preguntaron cómo había vivido yo tanto
tiempo con él. Pero Sebastian Euethorp me dijo,
para mi gran consuelo, que mi padrastro no tenía nada contra mí,
excepto lo concerniente a la ley de mi Dios.
Este es el sentido, si no las palabras,
que estos hombres sabios y buenos cruzaron entre ellos y mi padrastro,
como más tarde me lo contaron, porque yo no estaba ahí cuando ellos se reunieron.

Aunque yo le supliqué a mi padrastro que me dejara
quedarme hasta que pudiera oír de un lugar de trabajo,
él no quiso,
aunque realmente no era apto para ningún tipo de servicio al ser casi solo piel y huesos,
como dice el dicho, de modo que la mayoría de los que me conocían decían,
que seguramente me consumiría la tuberculosis.
Pero resulta que debía irme y lo hice, aunque era débil, pobre y humilde en cuerpo,
mente, bolsillo y ropas; porque creo que no tenía más de doce peniques en mi bolsillo,
y ropa común y corriente en mi espalda.
Así que me despedí solemnemente de la familia, con mi corazón lleno,
pero manteniéndome internamente vuelto hacia el Señor y bajo el gobierno de la Verdad.
Se derramaron muchas lágrimas cuando me fui, especialmente de parte de mi pobre madre.
Mi padrastro dijo muy poco,
pero parecía maravillado de ver cuánto amor me manifestaban
los otros miembros de la familia,
y lo mucho que deseaban que yo no tuviera que irme.

Salí a los grandes campos antes mencionados,
donde había hecho muchas caminatas en solitario, pero ninguna había sido como esta,
porque esta vez no sabía adónde ir.
Entonces pensé en Abraham, cuando fue llamado a salir de Ur, en la tierra de los caldeos;
pero había una diferencia entre nosotros: Que él había sido llamado,
yo había sido forzado a salir.
Yo tenía muchos amigos, pero no me sentía libre de ir a ellos,
porque no creía que tuvieran algún trabajo para mí;
ya que yo no era de una disposición atrevida, sino más bien retraída y tímida.
Mientras caminaba por los campos sin saber adónde ir o dónde recostar mi cabeza,
el sentido de mi débil condición me sobrecogió a tal grado,
que parecía que mi camino estuviera cercado por todo lado, interna y externamente.
Yo pensaba de mí mismo como un pelicano en el desierto,
o como un búho en regiones desoladas,
y me parecía que no había otro hombre en toda la tierra en mi misma
condición. En la consciencia y consideración de mi estado de abandono,
me sentí bajo una gran opresión de espíritu y con mi corazón
tan cargado que parecía una botella a punto de explotar.
Miré a mi alrededor para asegurarme que no había nadie cerca
que pudiera ver mis lágrimas ni oír mis clamores,
y en la angustia y amargura de mi alma, derramé mis quejas,
clamores y lágrimas delante del Juez de toda la tierra.
El Señor me consoló en mi deplorable estado, y me dijo,
como si un hombre me hubiera hablado:
"`Busca primero el reino de los cielos y su justicia,
y todas estas cosas de las que tienes necesidad, te serán dadas.`"
Entonces deseé que Él se complaciera en mostrarme un lugar adonde ir,
y el Señor abrió mi camino y me mostró la casa a
la que debía ir y permanecer por un tiempo.
Dije: "`Buena es la palabra del Señor.`" Yo Le creí,
y esto fue un gran medio para fijar mi mente y establecerla en la Verdad,
con plena intención de corazón de seguir al Señor y obedecer Sus requisitos,
según me daba conocimiento y habilidad.

Me fui a la casa de este Amigo en South Cliff, de nombre William Allon,
y pronto me uní a él como aprendiz de su oficio de tejedor.
Después de unirme a él, encontré que este buen hombre me amaba,
y yo lo amé hasta el día de su muerte.
Él a menudo decía que él y todo lo que le pertenecía había sido bendecido por mi causa,
porque él era muy pobre,
pero creció considerablemente después que yo llegué a vivir con él.

Tres cosas se interpusieron en mi camino para responder
plenamente a los mandatos del Señor como debía hacerlo.
Primero,
una dolorosa enfermedad se apoderó de mis piernas poco después de empezar como aprendiz,
la cual yo (y otros) pensaba que era mayormente ocasionada por el duro uso,
y calores y fríos en exceso, incluso desde mi infancia.
La cojera me retuvo cerca de dos años, y eso me desanimó e incapacitó mucho.
El segundo estorbo eran mi pobres circunstancias en el mundo,
las cuales muy pocos conocían,
porque el pensamiento común era que yo tenía padres
ricos (lo que no estaba exento de cierta verdad).
Pocos sabían las dificultades que yo enfrentaba, sin embargo,
si mi verdadero maestro religioso se percataba de que había algo
en mi mente con respecto a visitar alguna reunión o reuniones,
decía: "`Toma mi yegua y haz tu camino,
no estés intranquilo ni por la yegua ni por el negocio, y no te apresures.`"
Tales actos de amabilidad hacían que a menudo me preguntara,
cómo podría retribuirle suficientemente y estar debidamente agradecido por su amor.

Yo era diligente en el negocio de mi maestro, no sirviendo al ojo, sino fielmente,
creyendo que era bueno y aceptable ante los ojos de Dios; y en esto tenía gran paz.
Mi maestro nunca me reprochó por haber hecho muy poco, sino por haber hecho demasiado,
y a veces decía: "`¡Creo que te vas a pegar al travesaño del telar!
Salgamos y caminemos por el campo y veamos cómo están las cosas ahí.`" La sanidad
de mi pierna la atribuyo a la grande y buena providencia de Dios,
porque poco tiempo después de entregarme libre y alegremente
a responder a lo que el Señor requiriera de mí,
Él me sanó de la cojera.

El tercer estorbo era mi tartamudez;
yo clamaba al Señor creyendo que Él era capaz de quitar este impedimento,
como había detenido la violenta enfermedad de mi cuerpo.
Varios hombres entendidos habían dado su consejo y mostrado sus habilidades,
todo lo cual probó ser ineficaz.
Pero llegué a creer en Jesucristo y a echarlo todo sobre Él,
y tocar el borde de Su vestido, es decir,
la más pequeña aparición de Su bendita verdad y poder,
en la que encontré verdadera virtud sanadora para mi alma,
para mi cuerpo y para mi lengua también,
incluso para admiración mía. Entonces llegué a hablar claramente,
no sólo cuando daba el testimonio que el Señor me había mandado llevar,
sino también cuando interactuaba comúnmente con los hombres.

En aquellos días yo estaba bajo la dispensación de revelaciones y visiones,
y por decirlo así, me vi en el Monte Pisga,
viendo hacia la Tierra Santa y hacia las cosas relacionadas con Dios y Su reino celestial.
Vi claramente la obra de Dios y la forma de sacar al hombre de la caída y separación,
para llevarlo de nuevo a Él y al estado celestial en Cristo,
en tanto este le rinda verdadera obediencia a la dirección y operación de Su bendita
gracia y Espíritu Santo en el corazón. Pero bajo tales dispensaciones es de absoluta
necesidad que el hombre sea llevado a la verdadera negación del yo,
a un estado de ánimo de total dependencia,
y a la entrega de su voluntad a la voluntad de Dios,
diariamente sentado '`en el polvo`' con respecto a los movimientos y obras de la criatura.
Porque todo lo que es obra del hombre no hace más que estorbar la obra
espiritual de Dios en el corazón. Nosotros debemos llegar a experimentar,
verdaderamente,
todos los movimientos carnales y el funcionamiento de la
voluntad y del espíritu propios del hombre silenciados,
a fin de que oigamos la suave y apacible voz de Dios.
De hecho, Su voz no es oída en medio del ruido y la prisa del mundo,
ni cuando la mente está ocupada con cosas agradables
a nuestras voluntades corruptas y depravada naturaleza.

Aunque yo tenía visiones claras de muchas cosas celestiales,
y en ocasiones disfrutaba también de la consoladora presencia viva de Dios,
todavía tenía la necesidad de ser más establecido en la inmutable Verdad.
En mi clamor al Señor hallé que Él se inclinaba hacia mí y oía mis clamores,
y como dijo David,
"`me sacó del lodo cenagoso y puso mis pies sobre una peña`" que era más alta que yo,
"`enderezó mis pasos y puso en mi boca cántico nuevo,`" es decir,
grandes alabanzas al Señor por toda Su tierna misericordia
hacia mí en esos tiempos de prueba.
Estando, entonces, más crucificado al mundo y al espíritu de este,
experimenté que Su poder celestial y presencia viva,
luz y gracia moraban con más constancia en mí. Fui llevado a la quietud,
y descubrí que era más agradable para mi condición mantenerme en silencio,
esperando en el Señor la renovación de la fuerza,
para que así yo pudiera vencer todas las tentaciones
y pruebas con las que era tratado (que no eran pocas).
Estas son cosas dignas de recordar y demostraron ser grandes confirmaciones
en la Verdad en aquellos días de tribulación y grandes pruebas.
¡Lean y crean, los que puedan, porque son palabras fieles y verdaderas!

Después de que el Señor me sanara, me envió a la obra del ministerio,
y el primer viaje que hice fue hacia el sur a Lincolnshire,
Nottinghamshire y a través de Coventry, y así a Warwick para ver a William Dewsbury.^
footnote:[William Dewsbury (1621 - 1688) fue uno
de los primeros ministros en la Sociedad de Amigos,
y aunque pasó la mayoría de su vida adulta encarcelado por el testimonio de Jesús,
fue considerado por todos un pilar y anciano de la casa de Dios.]
Él me preguntó por la ruta que había seguido,
y yo le hice un relato de los pueblos y lugares en particular por los que había pasado,
mencionando que Coventry había sido el último y el peor.
Pues en Coventry, mientras hablaba en la reunión,
algunas personas groseras me habían lanzado piedras con gran violencia,
que si el Señor les hubiera permitido golpearme,
con toda seguridad me habrían hecho daño. Pero mi fe en el Señor y la fuerza de la Verdad,
sostuvieron mi mente por encima del temor de lo que
esos malvados me hubieran podido hacer.
Después de que William escuchó mi relato, fijó sus ojos en mí y me dijo:
"`Tienes que regresar a Coventry.`"
Yo estaba poco dispuesto por dos razones: Primero,
porque pensé que había acabado mi deber con esas personas.
Segundo, porque pensaba que no era seguro correr de regreso al peligro,
a menos que estuviera convencido de que el Señor lo requería
de mí. Pero William estaba seguro y me dijo que debía ir,
porque ahí había un servicio que yo debía cumplir.
Tras una deliberada consideración y búsqueda del
Señor para conocer Su voluntad en este asunto,
me sentí libre para regresar.
Y de hecho, descubrí que tenía algo que hacer ahí,
porque se había dado un mal entendido entre algunos Amigos en esa ciudad,
y esta vez al dejarlos,
quedaron mucho más unidos el uno al otro que cuando me reuní con ellos la primera vez,
para mi satisfacción.

Cuando regresé a casa después de esto y de todos mis viajes,
procuré dedicarme (hasta donde mi débil cuerpo fue capaz) al negocio,
y a no perder mi tiempo en casa ni fuera de casa.
Mi débil constitución física no soportaba bien el oficio de tejedor,
por tanto lo dejé contra mi voluntad y tomé el trabajo de
relojero (y muchas otras cosas) a fin de suplir mis necesidades.
El Señor siempre me permitía quedarme en casa tanto tiempo como me fuera necesario,
para ponerme en condiciones de viajar, y luego me inclinaba a ir y visitar Amigos.
Omito muchas cosas porque no quiero alargar demasiado mi relato,
pero viajé a través de la mayor parte de Inglaterra cuatro veces,
y dos por la mayor parte de Gales, entre el vigésimo y vigésimo octavo año de edad.

Después de que el Señor abriera mi corazón, llegué,
(en alguna medida) a entender las Sagradas Escrituras,
y a experimentar al Espíritu Santo en el que los santos escritores las habían escrito.
También sentía una medida de solidaridad con los espíritus
y ejercicios de los justos mencionados en ellas.
Yo me deleitaba leyéndolas, y al tener buena memoria,
podía lidiar mejor con la oposición de los sacerdotes y profesantes de varias denominaciones,
con quienes había tenido disputas y razonamientos en mis viajes,
tanto en Yorkshire como en otras partes.
Sin embargo, a través de esas disputas y la mucha lectura,
mi mente llegó a estar demasiado ocupada en la letra escrita,
y no tanto en el Espíritu y poder, como debía ser.
Debido a esto,
me topé con una amable advertencia de parte del Señor. Oí la voz del Señor tan claramente,
como si alguien me hubiera hablado al oído externo diciendo:
"`Las aves del cielo anidan en las ramas`"; y esto me fue repetido.
Así que busqué al Señor para que me mostrara cual era el
significado de esa voz que había oído. Entonces el Señor,
el poderoso Dios, me mostró (en Su misericordioso amor) que las Escrituras,
las cuales fueron escritas según fueron movidos los hombres por el Espíritu Santo,
brotaron de la raíz viva, y aún así,
que aquellos que descansan sólo en la letra y no se familiarizan,
viven y ministran desde el mismo Espíritu Santo, son externos, muertos, secos,
livianos y necios.

Esta gentil advertencia fue de gran utilidad para mí,
no en cuanto a hacerme declinar la lectura de las Escrituras,
sino para que yo no tuviera demasiada dependencia de ellas,
y para prevenirme contra el descuido de no esperar la ayuda del Espíritu Santo.
Porque en verdad,
el Espíritu es la raíz y la fuente pura de todo ministerio correcto y vivo,
el único que puede alcanzar el corazón y llevar la verdadera
evidencia a los creyentes de que este es de Dios;
lo que la letra escrita no puede hacer por sí misma.
Deseo tiernamente que todos los interesados en la gran obra del ministerio,
no sean sólo ministros de la letra, sino del Espíritu también,
y hablen en la demostración del Espíritu y poder.
"`Si alguno habla, sea como los oráculos de Dios; si alguno ministra,
sea como del poder que suministra Dios.`"^
footnote:[1 Pedro 4:11, Versión H.B. Pratt 1929.]
Este es el último y perpetuo ministerio,
el cual es según el orden de Melquisedec y no según
el orden de Aarón. Este ministerio es en Jesucristo,
el Sumo Sacerdote,
la única ofrenda que hace perfectos para siempre a todos
los que vienen a Él a través de las persuasiones del Padre.
Él es el único Señor, y no hay más que una fe en Él,
y un bautismo verdadero y salvador en Él, o en la semejanza de Su muerte.
Así como Cristo murió por el pecado,
así también nosotros podemos verdaderamente morir al pecado;
así como Él fue levantado por la gloria del Padre,
así también nosotros podemos andar en novedad de vida.
Él es el Sumo Sacerdote celestial, santo, inocente, separado de los pecadores,
el que fue tentado y sabe cómo socorrer a los que son tentados.
Él es el abogado ante el Padre, la propiciación por los pecados de todos,
el verdadero guía y consolador,
el que conduce a toda verdad a los que lo obedecen y siguen;
aunque para el mundo es un amonestador,
y un veloz testigo contra toda impiedad e injusticia de los hombres.

Mi escrito en este sentido,
acerca de esta gentil advertencia del Señor con respecto a las aves y las ramas,
no tiene la menor intención ni de minimizar las Sagradas Escrituras,
ni desanimar a nadie que las lea;
porque yo animo a todos los verdaderos cristianos a que sean más versados en ellas.
Sin embargo, mi consejo, amable lector, de tu bien intencionado y verdadero amigo,
es que anheles y verdaderamente vayas en pos del Señor en
busca de una medida de Su santo y bendito Espíritu,
quien es la única llave y el mejor expositor para abrirlas y mostrártelas.
Es por medio de este mismo Santo Espíritu que tu mente y
entendimiento llegan a ser preparados e iluminados.
De hecho, la vasija completa debe ser llevada a una preparación,
para contener el tesoro celestial y no mezclar lo puro con lo corrupto e impuro.
Porque sin el don de la santa gracia y Espíritu de Dios que ilumina, prepara,
revela y santifica, el hombre no puede conocer el poder celestial de Dios,
ni conocer las Sagradas Escrituras como debe conocerlas.
Por esta razón le ha parecido bueno a Dios esconder estas cosas de los doctos,
sabios y entendidos de este mundo, para que no interfieran,
ni descubran los misterios contenidos en ellas,
a menos que sean santificados y llamados por Dios a eso.
Así como nadie conoce las cosas del hombre,
excepto el espíritu del hombre que está en él,
igualmente las cosas de Dios no son perceptibles por el
hombre sin la ayuda del Espíritu Santo de Dios en el hombre.

Así fue como el Señor me reveló el verdadero significado
de la parábola de la semilla de mostaza,
en mi infancia en el ministerio,
con la que Él me envió al mundo para que mi fe estuviera fundada sólo en el Señor,
quien es el autor y consumador, así como el dador de esta fe verdadera y salvadora;
es decir, la fe que "`obra por amor`" y "`vence al mundo.`"
Fue por y a través del poder y eficacia de la verdadera fe (que es don de Dios),
que muchos en épocas pasadas y muchos ahora, alcanzan buen testimonio.
A través de este don el digno Abel, con su ofrenda, fue aceptado por Dios,
aunque era envidiado por su malvado hermano Caín,
y asesinado también por él. El siempre memorable Enoc,
a través de la virtud de este santo don, caminó con Dios,
y Dios mismo dio testimonio de que Enoc lo había complacido.
Este hombre caminó en fe y obediencia hasta el final,
tanto que él no murió como los hombres lo hacen comúnmente,
sino que fue traspuesto o cambiado de manera particular.
¡Vengan, lean, ustedes que pueden, y entiendan ustedes,
los redimidos del poder de la primera naturaleza, que han vencido la carne,
el mundo y al diablo en gran medida!
Porque ustedes saben que es por la operación de este don,
que los muertos en el primer Adán son levantados a una nueva
vida y a nueva forma de vida en el nuevo Hombre,
a través del poder del Adán celestial,
a quien ellos conocen como un Espíritu vivificador, conforme a las Escrituras.
A través de la fe se apagaron fuegos impetuosos, se taparon bocas de leones,
se evitaron filos de espadas, se pusieron en fuga ejércitos extranjeros, es decir,
aquellos ejércitos que eran ajenos o extraños a Dios,
y que pelearon externamente contra el pueblo del Señor en aquel día. Y de hecho,
esto pone delante de nosotros, como un espejo o figura,
cómo y qué debemos vencer en el día del evangelio.
Porque en el día del evangelio no debemos pelear con los hombres,
sino contra nuestras propias lujurias, vencer el pecado y a Satanás,
la cual es una gran victoria como la que venció los voraces leones.
Pues el pecado y Satanás son los que tienen poder
y dominio sobre el malvado e impío de hoy.

¡Ustedes que leen estas líneas, presten atención mientras todavía hay tiempo,
si Cristo o el anticristo predomina en ustedes,
si la gracia o el pecado es lo que más abunda en sus cuerpos
mortales! ¡Consideren si el Espíritu de Verdad,
que guía a toda verdad, o el espíritu de error, que guía a todo error y falsedad,
es el que prevalece y tiene mayor lugar en sus corazones!
Porque ustedes son siervos de aquel a quien estén más sujetos
y al que le presenten sus miembros en servidumbre.
Con el tiempo llegarán a ser completamente siervos y recibirán
al final de su jornada el salario que se le debe a los siervos,
de aquel a quien ustedes se rindan y se sujeten a sí mismos.
Por tanto,
presten atención en el tiempo oportuno mientras el
día de la visitación aún continúa para ustedes,
y mientras el Señor los sigue y los llama mediante Sus secretas advertencias y reprimendas,
por medio de las que Él intranquiliza sus mentes.
Porque aunque puedan sobreponerse al Testigo justo de Dios en sus
propias almas y deleitarse en la vanidad y caminos equivocados,
mientras Él aún se esfuerza por convertirlos y reunirlos
fuera de los placeres terrenales y sin sustancia,
y fijar sus mentes en las cosas celestiales y gozarse en ellas,
ustedes no tendrán verdadero consuelo en todos esos disfrutes inferiores,
sino que los acompañarán la condenación y angustia de alma hasta
que pisoteen al Testigo en sus corazones o dejen el mal.
Esta es la experiencia del pueblo del Señor,
el que se ha familiarizado con la verdadera guerra
interior y con la victoria de los santos.
¡Aprendan a seguir a Cristo por las pisadas de los rebaños de Sus compañeros,
aunque sea a través de grandes tribulaciones,
porque esta es la manera de tener los vestidos lavados y emblanquecidos
en la mística sangre del inmaculado Cordero de Dios!
Este es Aquel, como dijo Juan el Bautista, que quita los pecados del mundo.
¡Feliz todo el que verdaderamente se viste de Su naturaleza de cordero, de Su humildad,
justicia y pureza, es cubierto con Su Espíritu Santo,
y vive y camina en y bajo la influencia y dirección de eso hasta el fin de los tiempos!

[.asterism]
'''

__La larga y fructífera vida de John Richardson fue en verdad,
"`grato olor de Cristo entre los que se salvan y entre los que se pierden.`"
Continuó viajando como ministro hasta donde la fuerza física se lo permitió,
recorriendo varias veces la mayor parte de Inglaterra, Escocia e Irlanda,
y cruzando los mares dos veces para ministrar en las colonias en América.
Vivió hasta los 86 años, e incluso en sus años en declive,
sus amigos dieron este testimonio de él:
"`Cuando sus facultades naturales estaban de algún modo deterioradas
y estaba confinado en la casa por la vejez y las enfermedades,
él parecía tener más y más mente celestial y crecer en la vida de la religión.`"__

__En 1740, cuando John Richardson tenía 73 años,
Samuel Fothergill (para ese entonces un ministro joven en
la Sociedad) se quedó una noche en la casa de Richardson,
y le contó a su esposa lo siguiente en una carta:
"`Por la tarde cabalgué diez millas hasta la casa donde descansa el arca, es decir,
la de John Richardson, quien al día siguiente fue conmigo a Pickering.
La vida de la Verdad se levantó maravillosamente (en la reunión),
y luego ese Padre de Israel me llevó a casa,
donde nos sentamos a conversar hasta casi el amanecer.
Luego nos retiramos a nuestros respectivos alojamientos,
pero poco después de las cinco de la mañana vino y sentó al lado de mi cama,
y aunque estaba débil y muy mal,
dijo que él me acompañaría unas diez millas hacia Malton.`"__
